### ISSUE TITLE
챗봇 기록 저장을 위한 entity 작성

### ISSUE THREAD

**Issue by DongHyeonka** [team-jung-ppo/bamboo-forest_backend#12]
## 🔨 상세 작업 내용

- [x] 챗봇 방을 저장할 entity 작성
- [x] 채팅 내용을 저장할 entity 작성

## 📄 참고 사항
없음

**Comment by joon6093** [comment]
기능 단위로 이슈를 만들어주세요. ex) 챗봇 연결을 위한 websocket 연결 기능 구현
