### ISSUE TITLE
ChatBot 정보를 Entity가 아닌 Enum으로 관리하자는 토의

### ISSUE THREAD

**Issue by joon6093** [team-jung-ppo/bamboo-forest_backend#19]
## 🤷 토의 주제
ChatBot 정보를 Entity가 아닌 Enum으로 관리하는건 어떤가요?

## 📄 자신의 생각
1. **어드민 설계 부재**: 현재 어드민 시스템 설계가 없기 때문에, Entity로 관리할 경우 직접 DML을 이용해서 데이터를 삽입해야 하는 불편함이 있습니다.
2. **JPA 관리 어려움**: Entity로 제공할 경우, JPA적인 측면에서도 관리가 어렵고 복잡해질 수 있습니다.

## 👄 같이 생각했으면 하는 점
1. **확장성 문제**: 새로운 챗봇 종류를 추가할 때마다 Enum을 수정해야 하는 불편함이 있을 수 있습니다. 이로 인해 Enum이 커지면 관리가 어려울 수 있습니다.

**Comment by DongHyeonka** [comment]
아직은 챗봇의 종류가 적기도 하고 Enum으로 관리하는게 좋다고 생각합니다! 확장성의 문제는 나중에 생각하는걸로 해요!
